version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless # TODO: Use the dependency in node_modules..
  build:
    commands:
      - npm run create_domain -- --stage ${RF_ENVIRONMENT}
      - npm run deploy -- --verbose --stage ${RF_ENVIRONMENT} --region ${RF_REGION}
